version: "3.8"

services:
  dev-app:
    build:
      context: .
      dockerfile: dev-php.dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8000"

  dev-node:
    build:
      context: .
      dockerfile: dev-node.dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/app
    ports:
      - "5173:5173"

  mysql:
    image: mariadb:10.8.3
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: laravel
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  composer:
    image: composer/composer:2.5.4
    working_dir: /var/www/app
    entrypoint:
      - composer
    volumes:
      - .:/var/www/app

  artisan:
    image: php:8.2-fpm-alpine3.17
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    entrypoint:
      - php
      - /var/www/app/artisan

  npm:
    image: node:18.14-alpine3.17
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    entrypoint:
      - npm

networks:
  app-network:
    driver: bridge

volumes:
  db-data: { }
