version: "3"

services:
  broker:
    build:
      context: broker
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - golang

  web:
    build:
      context: frontend
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - golang

networks:
  golang: { }
