apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api
    spec:
      containers:
        - name: tasks-api
          image: matheusdr/kub-first-app:tasks-api
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              value: auth-svc.default
            - name: TASKS_FOLDER
              value: tasks
          volumeMounts:
            - mountPath: /app/tasks
              name: tasks-vol-empty-dir
      volumes:
        - name: tasks-vol-empty-dir
          emptyDir: { }
