apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}
data:
  #  default.json: |
  #{{ .Files.Get "default.json" | indent 4 }}
{{ (.Files.Glob "config/*").AsConfig | indent 4 }}
