name: Deployment Exercise 1
on: [ push ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Lint project
        run: yarn lint
      - name: Test project
        run: yarn test
      - name: Build project
        run: yarn build
      - name: Deploy project
        run: echo "Deploying project..."
