version: "3.8"

services:
  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db
    container_name: mongodb
#    environment:
#      MONGO_INITDB_USERNAME: root
#      MONGO_INITDB_PASSWORD: secret
    env_file:
      - ./env/mongo.env


  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    container_name: server
    env_file:
      - env/server.env

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src
    container_name: client
    stdin_open: true
    tty: true

volumes:
  mongo-data: { }
  logs: { }
