apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
  #    matchExpressions:
  #      - key: app
  #        operator: In
  #        values:
  #          - second-app
  #      - key: tier
  #        operator: In
  #        values:
  #          - backend
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-app
          image: matheusdr/kub-first-app:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            periodSeconds: 10
            initialDelaySeconds: 5
