name: Deploy to AWS S3
description: Deploy a static website via S3
inputs:
  bucket-name:
    description: The S3 bucket name
    required: true
  region:
    description: The region of the S3 required
    required: false
    default: us-east-1
  dist-folder:
    description: The folder containing the deployed files
    required: true
outputs:
  website-url:
    description: The url of the deployed website
runs:
  using: node16
  main: main.js
