- name: Overview of Methods and Filter
  hosts: localhost
  vars:
    a: HELLO
    d: hello
    b: 10
    c: 20
  tasks:
    - name: Operations in vars
      debug:
        msg:
          - 'Value of B is: {{ b }} and C is: {{ c }}'
          - 'b > c: {{ b > c }}'
          - 'b < c: {{ b < c }}'
          - 'b == c: {{ b == c }}'
          - 'b != c: {{ b != c }}'
          - 'b >= c: {{ b >= c }}'
          - 'b <= c: {{ b <= c }}'
          - 'Value of A is: {{ a }} and D is: {{ d }}'
          - 'a > d: {{ a > d }}'
          - 'a < d: {{ a < d }}'
          - 'a == d: {{ a == d }}'
          - 'a != d: {{ a != d }}'
          - 'a >= d: {{ a >= d }}'
          - 'a <= d: {{ a <= d }}'
          - 'lower a == d: {{ a|lower == d }}'
