- name: Overview of Methods and Filter
  hosts: localhost
  vars:
    a: Hello team, this is matheus-dr
    b: 10
    c: "20"
  tasks:
    - name: Operations in vars
      debug:
        msg:
          - 'Value of A is: {{ a }}'
          - 'Value of B + C is: {{ b + c|int }}'
          - 'Small case of A: {{ a|lower }}'
          - 'Upper case of A with filter: {{ a|upper }}'
          - 'Title case of A with filter: {{ a|title }}'
          - 'Small case of A with method: {{ a.lower() }}'
          - 'Upper case of A with method: {{ a.upper() }}'
          - 'List made by values of A: {{ a.split() }}'
