version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/web.dockerfile
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/app.dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html:delegated
  db:
    image: mysql:5.7
    env_file:
      - ./env/db.env
  composer:
    build:
      context: .
      dockerfile: ./dockerfiles/composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: ./dockerfiles/app.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint:
      - php
      - /var/www/html/artisan
  npm:
    image: node:18.13-alpine
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint:
      - npm
