version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - $PWD/ansible:/var/jenkins_home/ansible
    networks:
      - jenkins-net

  remote-host:
    build:
      context: .
      dockerfile: ./centos7/Dockerfile
    container_name: remote-host
    networks:
      - jenkins-net

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "80:80"
    networks:
      - jenkins-net

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - jenkins-net

  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    hostname: gitlab.example.com
    ports:
      - "8090:80"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/data/gitlab
    networks:
      - jenkins-net

volumes:
  jenkins-data: { }
  db-data: { }
  gitlab-config: { }
  gitlab-logs: { }
  gitlab-data: { }

networks:
  jenkins-net: { }
