- name: Configure Kali
  hosts: all
  become: yes
  become_method: sudo
  vars:
    apt_repositories:
      - deb http://http.kali.org/kali kali-experimental main contrib non-free
    apt_packages:
      - git
      - net-tools
      - dnsutils
      - gr-gsm
      - metagoofil
  tasks:
    - name: Ensure apt repositories are present
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop: "{{ apt_repositories }}"

    - name: Ensure packages are present
      apt:
        name: "{{ apt_packages }}"
        update_cache: yes
        state: present

    - name: Ensure Sn1per repo is present
      git:
        repo: https://github.com/1N3/Sn1per.git
        clone: yes
        dest: "{{ ansible_user_dir }}"

    - name: Ensure Sn1per is installed
      shell:
        cmd: "{{ ansible_user_dir }}/install.sh"
        creates: /usr/bin/sniper
