#!/bin/bash

## Adds a repository with new charts
helm repo add bitnami https://charts.bitnami.com/bitnami

## List all available charts
helm repo list

## Searchs for charts that contain nginx in the name
helm search repo nginx

## Install nginx from bitnami repo, specifying the name of chart
helm install nginx01 bitnami/nginx

## Shows all charts installed in current namespace
helm list

## Lists all the versions available of a certain name in repository
helm search repo --versions nginx

## Install nginx from bitnami specyfing chart version
helm install nginx02 --version 12.0.1 bitnami/nginx

## Install nginx from bitnami and specifies the values for chart
helm install nginx03 --values "$(dirname -- "$0")/nginx/values.yml" --set service.port=8080 bitnami/nginx

## Updates nginx01 setting new values for it
helm upgrade nginx01 --set service.type=NodePort --set service.port=8080 bitnami/nginx

## Upgrades nginx02 by setting a new version of chart, while retaining the other values
helm upgrade nginx02 --version 13.1.2 --reuse-values bitnami/nginx 

## Uninstalls charts present in cluster
helm uninstall nginx01
helm uninstall nginx02
helm uninstall nginx03

## Tests what this helm installation is going to do in cluster
helm install nginx01 --values "$(dirname -- "$0")/nginx/values.yml" --set service.port=8080 --dry-run bitnami/nginx

## Get the notes generated by the chart
helm get notes nginx01

## Gets all the values of the chart
helm get values nginx01 --all

## Get the manifest of chart
helm get manifest nginx01

## Get the versions of the chart
helm history nginx01

## Fails and rollbacks the current helm chart
helm upgrade nginx01 --set service.type=invalid --reuse-values bitnami/nginx
helm rollback nginx01 1

## Uninstall charts but keeps history to rollback
helm uninstall nginx01 --keep-history

## Auto generates a name for the release
helm install bitnami/nginx --generate-name

## Creates namespace if not exists
helm install nginx01 -n web --create-namespace bitnami/nginx

## Upgrade, otherwise creates new release
helm upgrade --install nginx01 -n web --set service.port=80008 bitnami/nginx

## Wait to build be successfull, useful in CD pipelines
helm upgrade nginx01 -n web --set image.registry=invalid bitnami/nginx --wait --timeout 10s

## Creates a new chart and applies it
helm create myapp
helm install myapp01 myapp/

## Port forward in localhost
kubectl port-forward myapp01-pod-name 8080:80

## Packages app to tar file
helm package myapp/
